# Generated by Django 2.2.5 on 2019-11-09 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('codigo_version', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('fecha_release', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('P', 'Progreso'), ('R', 'Reparado')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='issue',
            name='fixed_in',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='issuetracker.Update'),
        ),
    ]
