# Generated by Django 2.2.5 on 2019-11-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracker', '0002_auto_20191109_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='issue_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(),
        ),
    ]
